name: Karate CI

on: push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Testing
        run: |
          echo Hello, world!
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Verify JDK
        run: |
          java -cp karate.jar --version
      - name: Run karate scripts
        run: |
          java -jar karate.jar src/demo/web/github.feature
          java -jar karate.jar src/demo/api/users.feature


